## LAB
uri: 'mysql+pymysql://tuantd:admin123@172.16.9.26:3306/cas_s3_lab'
sqlalchemy_pool_size: 20
sqlalchemy_max_overflow: 0
modifications: False
bundle_errors: True
secret: 'fti-cas'
s3_be_host: '0.0.0.0'
s3_be_port: 5000
# set minus time out jwt
jwt_time_out: 100
max_buckets: 200
static_web_url: '.staticweb-ss.fptcompute.com.vn'
endpoint_url: 'http://ss.fptcompute.com.vn/'
# ==write log== 1: true, 0: false
use_log_pg: 1
use_log_mg: 1
use_log_file: 1

s3_fox_cloud:
  name_or_id: name
  version: 1
  api_version: 1
  session: None
  endpoint: 'http://ss.fptcompute.com.vn'
  region_name: us

s3_api:
  username: 'admin'
  password: 'Cas@2023'
  host: 'http://172.16.2.32:8443'
  my_secret_jwt: 'fti_cas_s3'

s3_mongo_db:
  host: '172.16.9.11'
  port: 27017
  username: 'mdbadmin'
  password: 'BbJ1e&G8R6cu'
  db_name: 's3mongodb'
  db_collection: 's3mongodb'